# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'activerecord', '~> 6.1', '>= 6.1.3.2'
gem 'rake', '~> 13.0', '>= 13.0.3'
gem "sinatra-activerecord", "~> 2.0"
gem "pry", "~> 0.14.1"
gem "require_all", "~> 3.0"
gem "sqlite3", "~> 1.4"

gem "faker", "~> 2.18"
