export const stories = [
  {
    id: 1,
    title: "Au Naturale",
    summary: "dhfvksdjfglsdghldsjgh",
    body: "wwoooooooow",
    word: "Naturalism",
    definition:
      "Belief that the world can be explained in terms of natural forces  ",
    pronunciation: "Naturalism",
  },
  {
    title: "khhsdfgfaksjfhg",
    summary: "kshdfbkdsjh",
    body: "ksdjfhgdshgf",
    word: "Whiffet",
    definition: "Paltry person; little dog  ",
    pronunciation: "Wifet",
    id: 2,
  },
  {
    title: "sjhdfgaf",
    summary: "ksadhfdsj",
    body: "ksdhfbkdsjf",
    word: "Nocuous",
    definition: "Hurtful; noxious  ",
    pronunciation: "Nokuous",
    id: 3,
  },
  {
    title: "skdhfbdslj",
    summary: "kjjdsglsdhj",
    body: "ksjdhfbhlsjdfn",
    word: "Shrouds",
    definition: "Ropes supporting the mast of a ship  ",
    pronunciation: "Shrouts",
    id: 4,
  },
  {
    title: "wjfhdskfj",
    summary: "kshdfgkdsjh",
    body: "lsgjdshfglsjhfd",
    word: "Defervescence",
    definition: "Abatement of heat; coolness; decrease of fever  ",
    pronunciation: "Teferfessense",
    id: 5,
  },
  {
    title: "kfjdsfljb",
    summary: "ksjdfkdjs",
    body: "skdjfdsljf",
    word: "Milliammeter",
    definition: "Instrument for recording very small electrical currents  ",
    pronunciation: "Miliameter",
    id: 6,
  },
]
